name: Portfolio CI

on:
  push:
    branches:
      - master

jobs:
  validar-portfolio:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Verificar index.html
        run: |
          if [ ! -f index.html ]; then
            echo "Erro: index.html não encontrado"
            exit 1
          fi

      - name: Arquivo encontrado
        run: echo "index.html validado com sucesso"