name: Portfolio CI

on:
  push:
    branches:
      - master

jobs:
  validar-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Procurar arquivos SQL
        run: |
          quantidade=$(find . -name "*.sql" | wc -l)

          echo "Arquivos SQL encontrados: $quantidade"

          if [ "$quantidade" -eq 0 ]; then
            echo "Nenhum arquivo SQL encontrado"
            exit 1
          fi

      - name: Validação concluída
        run: echo "Pelo menos um arquivo SQL foi encontrado"